service: import-service

frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-lift
configValidationMode: warn

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: 
            - "s3:ListBucket"
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:DeleteObject"
            - "s3:CopyObject"
          Resource: 
            - "arn:aws:s3:::uploaded-hp"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: 
            - "arn:aws:s3:::uploaded-hp/*"
functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters: {
              querystrings: {
                name: true
              }
            } 
          cors: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3: 
          bucket: uploaded-hp
          event: s3:ObjectCreated:*
          rules: 
            - prefix: uploaded/
            - suffix: ''
          existing: true
